spring.application.name=EventNotification
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=8077

spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=sql.migration

kafka.topic=alert
spring.kafka.bootstrap-servers=${AIVEN_KAFKA_SERVER}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=classpath:ca.pem
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${AIVEN_USERNAME}" password="${AIVEN_PASSWORD}";
scheduler.time=0/15 * * * * *

jwt.expiration.time=86400000
jwt.secret.key=c2VjcmV0a2V5MTIzNDU2Nzg5MFRlc3RGb3JVc2luZzQ=

mailjet.secret.key=${MAIL_SECRET}
mailjet.api.key=${MAIL_API_KEY}

sender.email=souravk0322@gmail.com
